"""PostgreSQL storage for the case workspace."""

import json
import os
import hashlib
import hmac
import secrets
from datetime import datetime, timezone
from urllib.parse import quote_plus

from sqlalchemy import bindparam, create_engine, text

_engine = None


def _database_url():
    """
    Railway에서는 DATABASE_URL 사용을 권장합니다.

    DATABASE_URL이 없으면 PostgreSQL 표준 환경변수
    PGHOST / PGPORT / PGDATABASE / PGUSER / PGPASSWORD 조합도 지원합니다.
    """
    url = (os.getenv("DATABASE_URL") or "").strip()

    if url:
        if url.startswith("postgres://"):
            return "postgresql+psycopg://" + url[len("postgres://"):]
        if url.startswith("postgresql://"):
            return "postgresql+psycopg://" + url[len("postgresql://"):]
        return url

    host = (os.getenv("PGHOST") or "").strip()
    port = (os.getenv("PGPORT") or "5432").strip()
    database = (os.getenv("PGDATABASE") or "").strip()
    user = (os.getenv("PGUSER") or "").strip()
    password = os.getenv("PGPASSWORD") or ""

    if host and database and user:
        return (
            f"postgresql+psycopg://{quote_plus(user)}:{quote_plus(password)}"
            f"@{host}:{port}/{quote_plus(database)}"
        )

    raise RuntimeError(
        "PostgreSQL 연결정보가 없습니다. Railway에서 PostgreSQL 서비스를 추가한 뒤 "
        "앱 서비스 Variables에 DATABASE_URL=${{Postgres.DATABASE_URL}} 형태로 연결하세요."
    )


def get_engine():
    global _engine
    if _engine is None:
        _engine = create_engine(
            _database_url(),
            pool_pre_ping=True,
            pool_recycle=300,
        )
    return _engine


def _users_config():
    try:
        users = json.loads(os.getenv("CLAIM_USERS_JSON", ""))
    except (ValueError, TypeError) as exc:
        raise RuntimeError("CLAIM_USERS_JSON에 세 계정의 JSON 배열을 설정하세요.") from exc
    if not isinstance(users, list) or len(users) != 3:
        raise RuntimeError("CLAIM_USERS_JSON에는 정확히 세 계정이 필요합니다.")
    names = set()
    for user in users:
        if not isinstance(user, dict) or not isinstance(user.get("username"), str) or not isinstance(user.get("password"), str):
            raise RuntimeError("각 계정에 username과 password가 필요합니다.")
        name = user["username"].strip().lower()
        if not name or name in names or len(user["password"]) < 12:
            raise RuntimeError("서로 다른 사용자명과 12자 이상 비밀번호를 설정하세요.")
        names.add(name)
    owner = os.getenv("CLAIM_LEGACY_OWNER", "").strip().lower()
    if owner not in names:
        raise RuntimeError("CLAIM_LEGACY_OWNER를 기존 사건의 담당 사용자명으로 설정하세요.")
    return users, owner


def _hash_password(password, salt=None):
    salt = salt or secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, 600_000)
    return salt.hex() + ":" + digest.hex()


def _verify_password(password, stored):
    try:
        salt_hex, _ = stored.split(":", 1)
        expected = _hash_password(password, bytes.fromhex(salt_hex))
        return hmac.compare_digest(expected, stored)
    except (ValueError, AttributeError):
        return False


def initialize():
    users, legacy_owner = _users_config()
    engine = get_engine()
    with engine.begin() as db:
        db.execute(text("""
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                active BOOLEAN NOT NULL DEFAULT TRUE
            )
        """))
        names = []
        for user in users:
            name = user["username"].strip().lower()
            names.append(name)
            row = db.execute(text("SELECT password_hash FROM users WHERE username=:name"), {"name": name}).first()
            if row is None:
                db.execute(text("INSERT INTO users(username,password_hash) VALUES(:name,:hash)"),
                           {"name": name, "hash": _hash_password(user["password"])})
            elif not _verify_password(user["password"], row[0]):
                db.execute(text("UPDATE users SET password_hash=:hash WHERE username=:name"),
                           {"name": name, "hash": _hash_password(user["password"])})
        db.execute(text("UPDATE users SET active=(username IN :names)").bindparams(bindparam("names", expanding=True)), {"names": names})
        db.execute(text("""
            CREATE TABLE IF NOT EXISTS cases (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                injury TEXT NOT NULL,
                status TEXT NOT NULL,
                created_at TEXT NOT NULL,
                rows_json TEXT NOT NULL,
                notes TEXT NOT NULL DEFAULT ''
            )
        """))
        db.execute(text("ALTER TABLE cases ADD COLUMN IF NOT EXISTS owner_id BIGINT REFERENCES users(id)"))
        db.execute(text("UPDATE cases SET owner_id=(SELECT id FROM users WHERE username=:owner) WHERE owner_id IS NULL"),
                   {"owner": legacy_owner})
        db.execute(text("ALTER TABLE cases ALTER COLUMN owner_id SET NOT NULL"))
        db.execute(text("CREATE INDEX IF NOT EXISTS cases_owner_idx ON cases(owner_id, id DESC)"))

        db.execute(text("""
            CREATE TABLE IF NOT EXISTS documents (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
                filename TEXT NOT NULL,
                mime_type TEXT NOT NULL,
                content BYTEA NOT NULL,
                extracted_text TEXT NOT NULL DEFAULT '',
                analysis TEXT NOT NULL DEFAULT '',
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        """))


def authenticate(username, password):
    with get_engine().connect() as db:
        row = db.execute(text("SELECT id, username, password_hash FROM users WHERE username=:name AND active=TRUE"),
                         {"name": username.strip().lower()}).first()
    if row and _verify_password(password, row[2]):
        return (row[0], row[1])
    return None


def active_user(user_id, username):
    with get_engine().connect() as db:
        return db.execute(text("SELECT 1 FROM users WHERE id=:id AND username=:name AND active=TRUE"),
                          {"id": user_id, "name": username}).first() is not None


def list_cases(owner_id):
    engine = get_engine()
    with engine.connect() as db:
        result = db.execute(
            text("""
                SELECT id, name, injury, status, created_at, rows_json, notes
                FROM cases
                WHERE owner_id=:owner_id ORDER BY id DESC
            """), {"owner_id": owner_id}
        )
        return [tuple(row) for row in result]


def create_case(owner_id, name, injury, *, rows=None):
    engine = get_engine()
    with engine.begin() as db:
        return db.execute(
            text("""
                INSERT INTO cases(owner_id, name, injury, status, created_at, rows_json, notes)
                VALUES(:owner_id, :name, :injury, '접수', :created_at, :rows_json, '')
                RETURNING id
            """),
            {
                "owner_id": owner_id,
                "name": name,
                "injury": injury,
                "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
                "rows_json": json.dumps(rows if rows is not None else [], ensure_ascii=False),
            },
        ).scalar_one()


def save_case(owner_id, case_id, *, rows=None, status=None, notes=None):
    changes = {"id": case_id, "owner_id": owner_id}

    if rows is not None:
        changes["rows_json"] = json.dumps(rows, ensure_ascii=False)

    if status is not None:
        changes["status"] = status

    if notes is not None:
        changes["notes"] = notes

    if len(changes) == 2:
        return

    assignments = ", ".join(
        f"{key}=:{key}" for key in changes if key not in ("id", "owner_id")
    )

    engine = get_engine()
    with engine.begin() as db:
        db.execute(
            text(f"UPDATE cases SET {assignments} WHERE id=:id AND owner_id=:owner_id"),
            changes,
        )


def add_document(owner_id, case_id, filename, mime_type, content, extracted_text):
    engine = get_engine()
    with engine.begin() as db:
        return db.execute(
            text("""
                INSERT INTO documents(
                    case_id, filename, mime_type, content, extracted_text
                )
                SELECT :case_id, :filename, :mime_type, :content, :extracted_text
                WHERE EXISTS (SELECT 1 FROM cases WHERE id=:case_id AND owner_id=:owner_id)
                RETURNING id
            """),
            {
                "owner_id": owner_id,
                "case_id": case_id,
                "filename": filename,
                "mime_type": mime_type,
                "content": content,
                "extracted_text": extracted_text,
            },
        ).scalar_one()


def list_documents(owner_id, case_id):
    engine = get_engine()
    with engine.connect() as db:
        result = db.execute(
            text("""
                SELECT
                    id,
                    filename,
                    mime_type,
                    octet_length(content) AS size,
                    length(extracted_text) AS text_length,
                    analysis,
                    created_at
                FROM documents
                WHERE case_id=:id AND EXISTS
                    (SELECT 1 FROM cases WHERE id=:id AND owner_id=:owner_id)
                ORDER BY id DESC
            """),
            {"id": case_id, "owner_id": owner_id},
        )
        return [dict(row._mapping) for row in result]


def get_document(owner_id, case_id, document_id):
    engine = get_engine()
    with engine.connect() as db:
        row = db.execute(
            text("""
                SELECT *
                FROM documents
                WHERE case_id=:case_id AND id=:id AND EXISTS
                    (SELECT 1 FROM cases WHERE id=:case_id AND owner_id=:owner_id)
            """),
            {
                "case_id": case_id,
                "owner_id": owner_id,
                "id": document_id,
            },
        ).mappings().first()

        return dict(row) if row else None


def save_analysis(owner_id, case_id, document_id, analysis):
    engine = get_engine()
    with engine.begin() as db:
        db.execute(
            text("""
                UPDATE documents
                SET analysis=:analysis
                WHERE case_id=:case_id AND id=:id AND EXISTS
                    (SELECT 1 FROM cases WHERE id=:case_id AND owner_id=:owner_id)
            """),
            {
                "analysis": json.dumps(analysis, ensure_ascii=False),
                "case_id": case_id,
                "owner_id": owner_id,
                "id": document_id,
            },
        )
