"""PostgreSQL storage for the case workspace."""

import json
import os
from datetime import datetime, timezone
from urllib.parse import quote_plus

from sqlalchemy import create_engine, text

_engine = None


def _database_url():
    """
    Railway에서는 DATABASE_URL 사용을 권장합니다.

    DATABASE_URL이 없으면 PostgreSQL 표준 환경변수
    PGHOST / PGPORT / PGDATABASE / PGUSER / PGPASSWORD 조합도 지원합니다.
    """
    url = (os.getenv("DATABASE_URL") or "").strip()

    if url:
        if url.startswith("postgres://"):
            return "postgresql+psycopg://" + url[len("postgres://"):]
        if url.startswith("postgresql://"):
            return "postgresql+psycopg://" + url[len("postgresql://"):]
        return url

    host = (os.getenv("PGHOST") or "").strip()
    port = (os.getenv("PGPORT") or "5432").strip()
    database = (os.getenv("PGDATABASE") or "").strip()
    user = (os.getenv("PGUSER") or "").strip()
    password = os.getenv("PGPASSWORD") or ""

    if host and database and user:
        return (
            f"postgresql+psycopg://{quote_plus(user)}:{quote_plus(password)}"
            f"@{host}:{port}/{quote_plus(database)}"
        )

    raise RuntimeError(
        "PostgreSQL 연결정보가 없습니다. Railway에서 PostgreSQL 서비스를 추가한 뒤 "
        "앱 서비스 Variables에 DATABASE_URL=${{Postgres.DATABASE_URL}} 형태로 연결하세요."
    )


def get_engine():
    global _engine
    if _engine is None:
        _engine = create_engine(
            _database_url(),
            pool_pre_ping=True,
            pool_recycle=300,
        )
    return _engine


def initialize():
    engine = get_engine()
    with engine.begin() as db:
        db.execute(text("""
            CREATE TABLE IF NOT EXISTS cases (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                injury TEXT NOT NULL,
                status TEXT NOT NULL,
                created_at TEXT NOT NULL,
                rows_json TEXT NOT NULL,
                notes TEXT NOT NULL DEFAULT ''
            )
        """))

        db.execute(text("""
            CREATE TABLE IF NOT EXISTS documents (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
                filename TEXT NOT NULL,
                mime_type TEXT NOT NULL,
                content BYTEA NOT NULL,
                extracted_text TEXT NOT NULL DEFAULT '',
                analysis TEXT NOT NULL DEFAULT '',
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
        """))


def list_cases():
    engine = get_engine()
    with engine.connect() as db:
        result = db.execute(
            text("""
                SELECT id, name, injury, status, created_at, rows_json, notes
                FROM cases
                ORDER BY id DESC
            """)
        )
        return [tuple(row) for row in result]


def create_case(name, injury, *, rows=None):
    engine = get_engine()
    with engine.begin() as db:
        return db.execute(
            text("""
                INSERT INTO cases(name, injury, status, created_at, rows_json, notes)
                VALUES(:name, :injury, '접수', :created_at, :rows_json, '')
                RETURNING id
            """),
            {
                "name": name,
                "injury": injury,
                "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
                "rows_json": json.dumps(rows if rows is not None else [], ensure_ascii=False),
            },
        ).scalar_one()


def save_case(case_id, *, rows=None, status=None, notes=None):
    changes = {"id": case_id}

    if rows is not None:
        changes["rows_json"] = json.dumps(rows, ensure_ascii=False)

    if status is not None:
        changes["status"] = status

    if notes is not None:
        changes["notes"] = notes

    if len(changes) == 1:
        return

    assignments = ", ".join(
        f"{key}=:{key}" for key in changes if key != "id"
    )

    engine = get_engine()
    with engine.begin() as db:
        db.execute(
            text(f"UPDATE cases SET {assignments} WHERE id=:id"),
            changes,
        )


def add_document(case_id, filename, mime_type, content, extracted_text):
    engine = get_engine()
    with engine.begin() as db:
        return db.execute(
            text("""
                INSERT INTO documents(
                    case_id, filename, mime_type, content, extracted_text
                )
                VALUES(
                    :case_id, :filename, :mime_type, :content, :extracted_text
                )
                RETURNING id
            """),
            {
                "case_id": case_id,
                "filename": filename,
                "mime_type": mime_type,
                "content": content,
                "extracted_text": extracted_text,
            },
        ).scalar_one()


def list_documents(case_id):
    engine = get_engine()
    with engine.connect() as db:
        result = db.execute(
            text("""
                SELECT
                    id,
                    filename,
                    mime_type,
                    octet_length(content) AS size,
                    length(extracted_text) AS text_length,
                    analysis,
                    created_at
                FROM documents
                WHERE case_id=:id
                ORDER BY id DESC
            """),
            {"id": case_id},
        )
        return [dict(row._mapping) for row in result]


def get_document(case_id, document_id):
    engine = get_engine()
    with engine.connect() as db:
        row = db.execute(
            text("""
                SELECT *
                FROM documents
                WHERE case_id=:case_id AND id=:id
            """),
            {
                "case_id": case_id,
                "id": document_id,
            },
        ).mappings().first()

        return dict(row) if row else None


def save_analysis(case_id, document_id, analysis):
    engine = get_engine()
    with engine.begin() as db:
        db.execute(
            text("""
                UPDATE documents
                SET analysis=:analysis
                WHERE case_id=:case_id AND id=:id
            """),
            {
                "analysis": json.dumps(analysis, ensure_ascii=False),
                "case_id": case_id,
                "id": document_id,
            },
        )
