"""PostgreSQL storage for the case workspace."""
import json
import os
from datetime import datetime, timezone
from sqlalchemy import create_engine, text


def _url():
    url = os.getenv('DATABASE_URL', '')
    if not url:
        raise RuntimeError('DATABASE_URL을 설정하고 Railway PostgreSQL을 연결하세요.')
    return url.replace('postgres://', 'postgresql+psycopg://', 1).replace('postgresql://', 'postgresql+psycopg://', 1)


engine = create_engine(_url(), pool_pre_ping=True)


def initialize():
    with engine.begin() as db:
        db.execute(text('''CREATE TABLE IF NOT EXISTS cases (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL,
            injury TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL,
            rows_json TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '')'''))
        db.execute(text('''CREATE TABLE IF NOT EXISTS documents (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            case_id BIGINT NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
            filename TEXT NOT NULL, mime_type TEXT NOT NULL, content BYTEA NOT NULL,
            extracted_text TEXT NOT NULL DEFAULT '', analysis TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now())'''))


def list_cases():
    with engine.connect() as db:
        return [tuple(row) for row in db.execute(text('SELECT id,name,injury,status,created_at,rows_json,notes FROM cases ORDER BY id DESC'))]


def create_case(name, injury):
    with engine.begin() as db:
        return db.execute(text('''INSERT INTO cases(name,injury,status,created_at,rows_json,notes)
            VALUES(:name,:injury,'접수',:created_at,'[]','') RETURNING id'''),
            dict(name=name, injury=injury, created_at=datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC'))).scalar_one()


def save_case(case_id, *, rows=None, status=None, notes=None):
    changes = {'id': case_id}
    if rows is not None: changes['rows_json'] = json.dumps(rows, ensure_ascii=False)
    if status is not None: changes['status'] = status
    if notes is not None: changes['notes'] = notes
    if len(changes) == 1: return
    assignments = ', '.join(f'{key}=:{key}' for key in changes if key != 'id')
    with engine.begin() as db:
        db.execute(text(f'UPDATE cases SET {assignments} WHERE id=:id'), changes)


def add_document(case_id, filename, mime_type, content, extracted_text):
    with engine.begin() as db:
        return db.execute(text('''INSERT INTO documents(case_id,filename,mime_type,content,extracted_text)
            VALUES(:case_id,:filename,:mime_type,:content,:extracted_text) RETURNING id'''),
            dict(case_id=case_id, filename=filename, mime_type=mime_type, content=content, extracted_text=extracted_text)).scalar_one()


def list_documents(case_id):
    with engine.connect() as db:
        return [dict(row._mapping) for row in db.execute(text('''SELECT id,filename,mime_type,octet_length(content) AS size,
            length(extracted_text) AS text_length,analysis,created_at FROM documents WHERE case_id=:id ORDER BY id DESC'''), {'id':case_id})]


def get_document(case_id, document_id):
    with engine.connect() as db:
        row = db.execute(text('SELECT * FROM documents WHERE case_id=:case_id AND id=:id'), {'case_id':case_id,'id':document_id}).mappings().first()
        return dict(row) if row else None


def save_analysis(case_id, document_id, analysis):
    with engine.begin() as db:
        db.execute(text('UPDATE documents SET analysis=:analysis WHERE case_id=:case_id AND id=:id'),
            dict(analysis=json.dumps(analysis, ensure_ascii=False), case_id=case_id, id=document_id))
